# Generated by Django 5.0 on 2023-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
